repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      # # line length compatible with black and flake8
      - id: docformatter
        args: [--wrap-summaries, "79", --in-place]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      # Prevent giant files from being committed.
      - id: check-added-large-files
        args: ['--maxkb=500']

        # Simply check whether files parse as valid python.
      - id: check-ast

      # Attempts to load all json files to verify syntax.
      - id: check-json

      # Checks for symlinks which do not point to anything.
      - id: check-symlinks

      # Attempts to load all xml files to verify syntax.
      - id: check-xml

      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml

      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict

      # Attempts to load all TOML files to verify syntax.
      - id: check-toml

      # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: debug-statements

      # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: destroyed-symlinks

      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer

      # Assert that files in tests/ start in test_*.py.
      - id: name-tests-test
        args: ['--django']

      # Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0
      - id: requirements-txt-fixer

      # Trims trailing whitespace.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
    -   id: mypy

  # jupyter notebooks: clear output cells from the version control
  - repo: local
    hooks:
      - id: jupyter-clear-output
        name: jupyter-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

  # notebook checks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    - id: nbqa-ruff
    - id: nbqa-check-ast
      # custom hooks of nbqa
      # code is adapted from:
      # 1) nbQA/.pre-commit-hooks.yaml
      # 2) entry points were taken from pre-commit-hooks/setup.cfg
    - id: nbqa
      name: nbqa-merge-conflict
      description: "Run 'check_merge_conflict' on a Jupyter Notebook"
      entry: nbqa pre_commit_hooks.check_merge_conflict
      language: python
      require_serial: true
      types: [jupyter]
      additional_dependencies: [pre_commit_hooks==5.0.0]
    - id: nbqa
      name: nbqa-debug-statements
      description: "Run 'debug-statements' on a Jupyter Notebook"
      entry: nbqa pre_commit_hooks.debug_statement_hook
      language: python
      require_serial: true
      types: [jupyter]
      additional_dependencies: [pre_commit_hooks==5.0.0]
